replicaCount: 1

image: 
  digest: oznu/homebridge@sha256:ecf944ab0edc9fced9495ab9f9c52aff5bd86ab02c74dab883dc9a82d79a3eb9
  pullPolicy: IfNotPresent

environment:
  pgid: 0
  puid: 0
  ui:
    enabled: 1
    port: 80
  timezone: America/Los_Angeles
  packages: ffmpeg

ports:

  ui:
    name: ui-http
    number: 80
    protocol: TCP

  service:
    name: service-mdns
    number: 51826
    protocol: TCP

service:
  ip:

affinity:
  weight: 100
  label: 
  value:

config:
  configFile:
    enabled: true
    path: config/config.json
  packageFile:
    path: config/package.json