replicaCount: 1

image: 
  digest: oznu/homebridge@sha256:b6d397dd487068dfa20b0119ffd52135039675050d8e9e491e8554873d2121a4
  pullPolicy: IfNotPresent

environment:
  pgid: 1000
  puid: 1000
  ui:
    enabled: 1
    port: 80
  timezone: America/Los_Angeles
  packages: ffmpeg

ports:

  ui:
    name: ui-http
    number: 80
    protocol: TCP

  service:
    name: service-mdns
    number: 51826
    protocol: TCP

service:
  ip: 

config:
  configMapName: homebridge-config

storage:
  mountOptions: "vers=1.0,dir_mode=0755,file_mode=0644,noperm"

secrets:
  storage:
    name: homebridge-storage-secret
    networkPath:
    user:
    password: